version: '3'
services:
  db:
    image: mysql
    volumes:
        - ./mysql:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
        - 3306:3306
  php:
    build: build/php
    expose:
      - '9000'
    depends_on:
      - db
    volumes:
      - ./application:/var/www/html/application:cached
      - ./logs:/var/log
  web:
    build: build/nginx
    restart: always
    ports:
        - '80:80'
    volumes:
        - ./application:/var/www/html/application:cached
        - ./logs:/var/log/nginx